import { NextResponse } from 'next/server'
import { GoogleGenAI } from '@google/genai'
import fs from 'fs'
import path from 'path'

const ai = new GoogleGenAI({ apiKey: process.env.NANO_BANANA_API_KEY })

export async function POST(request: Request) {
  try {
    const { cause, level, currentLevel } = await request.json()
    console.log(`[Nano Banana API Triggered]: Generating ${cause} level ${level} (from ${currentLevel})`)

    const isNew = currentLevel === 0
    const templateName = isNew ? 'new_casue.md' : 'next_level.md'
    
    // Read the prompt template
    const templatePath = path.join(process.cwd(), 'image_gen', templateName)
    let promptTemplate = fs.readFileSync(templatePath, 'utf8')

    // Replace placeholders
    promptTemplate = promptTemplate
      .replace(/{CAUSE}/g, cause)
      .replace(/{BUILDING_TYPE}/g, cause + ' center')
      .replace(/{BUILDING_DESCRIPTION}/g, 'A central hub for ' + cause)
      .replace(/{CAUSE_COLOR}/g, 'Blue')
      .replace(/{CURRENT_LEVEL}/g, String(currentLevel))
      .replace(/{NEXT_LEVEL}/g, String(level))

    console.log('Sending request to Gemini 3.1 Flash Image...')

    let response;

    if (isNew) {
       // Use a default reference image for new buildings to set the style
       const refImagePath = path.join(process.cwd(), 'public', 'assets', 'buildings', 'climate_lvl1.png')
       let imageBytes = ''
       if (fs.existsSync(refImagePath)) {
           imageBytes = fs.readFileSync(refImagePath).toString('base64')
       }
       
       response = await ai.models.generateContent({
         model: 'gemini-3.1-flash-image',
         contents: imageBytes ? [
           { inlineData: { mimeType: 'image/png', data: imageBytes } },
           promptTemplate
         ] : promptTemplate,
       });
    } else {
       // Image-to-Image Edit
       const currentImagePath = path.join(process.cwd(), 'public', 'assets', 'buildings', `${cause}_lvl${currentLevel}.png`)
       let imageBytes = '';
       if (fs.existsSync(currentImagePath)) {
           imageBytes = fs.readFileSync(currentImagePath).toString('base64');
       }

       if (imageBytes) {
           response = await ai.models.generateContent({
             model: 'gemini-3.1-flash-image',
             contents: [
                { inlineData: { mimeType: 'image/png', data: imageBytes } },
                promptTemplate
             ]
           });
       } else {
           // Fallback to text to image if no image found
           response = await ai.models.generateContent({
             model: 'gemini-3.1-flash-image',
             contents: promptTemplate,
           });
       }
    }

    // Find the first part that contains inlineData (image might not be the very first part if text is prepended)
    const imagePart = response?.candidates?.[0]?.content?.parts?.find(p => p.inlineData)
    const base64Image = imagePart?.inlineData?.data
    
    if (!base64Image) {
      throw new Error("No image generated by the API: " + JSON.stringify(response.candidates?.[0]));
    }

    // Save image to public directory
    
    const imageBuffer = Buffer.from(base64Image, 'base64')
    const outputPath = path.join(process.cwd(), 'public', 'assets', 'buildings', `${cause}_lvl${level}.png`)
    
    // Make magenta background transparent
    const { Jimp } = require('jimp');
    const image = await Jimp.read(imageBuffer);
    
    const targetColor = { r: 255, g: 0, b: 255 }; // Target Magenta
    const colorDistance = (c1: any, c2: any) => Math.abs(c1.r - c2.r) + Math.abs(c1.g - c2.g) + Math.abs(c1.b - c2.b);
    const tolerance = 150; // Increased tolerance for magenta variations
    
    const w = image.bitmap.width;
    const h = image.bitmap.height;
    const visited = new Set();
    const queue = [
      {x: 0, y: 0}, {x: w-1, y: 0}, 
      {x: 0, y: h-1}, {x: w-1, y: h-1}
    ];
    
    while(queue.length > 0) {
      const {x, y} = queue.shift()!;
      const key = x + ',' + y;
      if (visited.has(key)) continue;
      if (x < 0 || x >= w || y < 0 || y >= h) continue;
      
      visited.add(key);
      const idx = (w * y + x) << 2;
      
      const r = image.bitmap.data[idx + 0];
      const g = image.bitmap.data[idx + 1];
      const b = image.bitmap.data[idx + 2];
      
      if (colorDistance({r,g,b}, targetColor) < tolerance) {
        image.bitmap.data[idx + 3] = 0; // Transparent
        
        if (!visited.has((x+1)+','+y)) queue.push({x: x+1, y});
        if (!visited.has((x-1)+','+y)) queue.push({x: x-1, y});
        if (!visited.has(x+','+(y+1))) queue.push({x, y: y+1});
        if (!visited.has(x+','+(y-1))) queue.push({x, y: y-1});
      }
    }
    
    // Resize to exact display resolution to prevent WebGL aliasing/pixelation
    image.resize({ w: 768, h: 512 }); // Jimp 1.6 uses standard signature: image.resize(w, h)
    
    await image.write(outputPath);

    
    return NextResponse.json({ 
      success: true, 
      message: 'Generated successfully',
      assetUrl: `/assets/buildings/${cause}_lvl${level}.png`
    })
  } catch (error: any) {
    console.error('Error generating building:', error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
